// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef FINGER_H
#define FINGER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 * This class encapsulates the Finger subsystem code that will actuate.
 */
class Finger: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	/*
	 * This is the physical pointer to the finger single solenoid.
	 */
	std::shared_ptr<DoubleSolenoid> solenoidFinger;
public:
	/*
	 * Initializes a new instance of the Finger class
	 */
	Finger();

	/*
	 * This method will set the default command of the finger subsystem (MoveFinger)
	 */
	void InitDefaultCommand();

	/*
	 * Extends the finger outward
	 */
	void In();

	/*
	 * Retracts the finger towards the robot
	 */
	void Out();

	/*
	 * Turns off the solenoid for the finger.
	 */
	void Off();
};

#endif
