// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef PNEUMATICS_H
#define PNEUMATICS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 * This class is the wrapper around the compressor start commands.
 */
class Pneumatics: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	/*
	 * This is the actual pointer to run the compressor
	 */
	std::shared_ptr<Compressor> compressor;
public:
	/*
	 * Initializes a new instance of the Pneumatics class.
	 */
	Pneumatics();

	/*
	 * Initializes the default command for the compressor (none, done in Robot.cpp)
	 */
	void InitDefaultCommand();
};

#endif
