// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "WheelieBar.h"
#include "../RobotMap.h"

#include "../Commands/MoveWheelieBar.h"

WheelieBar::WheelieBar() : Subsystem("WheelieBar") {
	solenoidWheeliebar = RobotMap::wheelieBarSolenoid;
}

void WheelieBar::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());

        SetDefaultCommand(new MoveWheelieBar(false, false));
}

void WheelieBar::Up(){
	solenoidWheeliebar->Set(DoubleSolenoid::Value::kForward);
}

void WheelieBar::Down() {
	solenoidWheeliebar->Set(DoubleSolenoid::Value::kReverse);
}

void WheelieBar::Off() {
	solenoidWheeliebar->Set(DoubleSolenoid::Value::kOff);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

