// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef WHEELIEBAR_H
#define WHEELIEBAR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 * This class contains all of the code to actually move the wheelie bar on the robot.
 */
class WheelieBar: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	/*
	 * This pointer will actually point to the physical wheelie bar double solenoid.
	 */
	std::shared_ptr<DoubleSolenoid> solenoidWheeliebar;

public:
	/*
	 * Initializes a new instance of the WheelieBar class.
	 */
	WheelieBar();

	/*
	 * This method sets up the default command for the wheelie bar (MoveWheelieBar)
	 */
	void InitDefaultCommand();

	/*
	 * This extends the wheelie bar to the down position
	 */
	void Up();

	/*
	 * This will fold up the wheelie bar for storage.
	 */
	void Down();

	/*
	 * This shuts down the double solenoid.
	 */
	void Off();
};

#endif
