// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "WheelieBar.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/MoveWheelieBar.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

WheelieBar::WheelieBar() : Subsystem("WheelieBar") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    sOLENOID_WHEELIEBAR = RobotMap::wheelieBarSOLENOID_WHEELIEBAR;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void WheelieBar::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new MoveWheelieBar(false, false));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void WheelieBar::Up(){
	sOLENOID_WHEELIEBAR->Set(DoubleSolenoid::Value::kForward);
}

void WheelieBar::Down() {
	sOLENOID_WHEELIEBAR->Set(DoubleSolenoid::Value::kReverse);
}

void WheelieBar::Off() {
	sOLENOID_WHEELIEBAR->Set(DoubleSolenoid::Value::kOff);
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

