// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<SpeedController> driveDriveMotorL1;
	static std::shared_ptr<SpeedController> driveDriveMotorL2;
	static std::shared_ptr<SpeedController> driveDriveMotorR1;
	static std::shared_ptr<SpeedController> driveDriveMotorR2;
	static std::shared_ptr<RobotDrive> driveRobotDrive41;
	static std::shared_ptr<DoubleSolenoid> wheelieBarSOLENOID_WHEELIEBAR;
	static std::shared_ptr<DoubleSolenoid> fingerSOLENOID_FINGER;
	static std::shared_ptr<DoubleSolenoid> elevatorSOLENOID_ELEVATOR;
	static std::shared_ptr<Compressor> pneumaticsCOMPRESSOR;
	static std::shared_ptr<SpeedController> armARM_MOTOR_1;
	static std::shared_ptr<SpeedController> armARM_MOTOR_2;
	static std::shared_ptr<SpeedController> collectorCOLLECTOR;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static std::shared_ptr<Encoder> encoder;


	//constants for the motor ports


	//Digital Inputs
	const int SOLENOID_FINGER = 2;
	const int SOLENOID_FINGER2 = 4;
	const int SOLENOID_ARM = 1;
	const int SOLENOID_ARM2 = 3;
	const int SOLENOID_WHEELIEBAR = 0;
	const int SOLENOID_WHEELIEBAR2 = 6;

	//Buttons for Right Joystick
	const int COLLECTOR_IN = 1;

	//Buttons for Left Joystick
	const int COLLECTOR_OUT = 1;

	//Buttons for operator Joystick
	const int ELEVATOR_BUTTON = 1;
	const int FINGER_BUTTON = 2;
	const int WHEELIEBAR_BUTTON = 3;

	static void init();
};
#endif
