// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

//constants for the motor ports
const int MOTOR_L1_PORT = 7;
const int MOTOR_L2_PORT = 4;
const int MOTOR_R1_PORT = 8;
const int MOTOR_R2_PORT = 0;
const int MOTOR_ARM1_PORT = 5;
const int MOTOR_ARM2_PORT = 9;
const int MOTOR_COLLECTOR_PORT = 1;

//Solenoid
const int WHEELIE_PORT_FORWARD = 1;
const int WHEELIE_PORT_REVERSE = 4;
const int FINGER_PORT_FORWARD = 0;
const int FINGER_PORT_REVERSE = 3;
const int ELEVATOR_PORT_FORWARD = 2;
const int ELEVATOR_PORT_REVERSE = 5;

//Digital Inputs
const int AUTO_LOWBAR_PIN = 1;
const int AUTO_MOAT_PIN = 2;
const int AUTO_PORTC_PIN = 3;
const int AUTO_ROUGHT_PIN = 4;
const int AUTO_RAMPART_PIN = 5;
const int AUTO_ROCKWALL_PIN = 6;
const int AUTO_CHEVAL_PIN = 7;

const int ARM_ENCODER_A_PORT = 20;
const int ARM_ENCODER_B_PORT = 21;

//Buttons for Right Joystick
const int COLLECTOR_IN = 1;

//Buttons for Left Joystick
const int COLLECTOR_OUT = 1;

//Buttons for operator Joystick
const int ELEVATOR_BUTTON = 1;
const int FINGER_BUTTON = 2;
const int WHEELIEBAR_BUTTON = 3;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	static std::shared_ptr<SpeedController> driveDriveMotorL1;
	static std::shared_ptr<SpeedController> driveDriveMotorL2;
	static std::shared_ptr<SpeedController> driveDriveMotorR1;
	static std::shared_ptr<SpeedController> driveDriveMotorR2;
	static std::shared_ptr<RobotDrive> driveRobotDrive41;
	static std::shared_ptr<DoubleSolenoid> wheelieBarSolenoid;
	static std::shared_ptr<DoubleSolenoid> fingerSolenoid;
	static std::shared_ptr<DoubleSolenoid> elevatorSolenoid;
	static std::shared_ptr<Compressor> compressor;
	static std::shared_ptr<SpeedController> armMotor1;
	static std::shared_ptr<SpeedController> armMotor2;
	static std::shared_ptr<SpeedController> collectorMotor;

	static std::shared_ptr<Encoder> encoder;

	static void init();
};
#endif
